### PR TITLE
Bump json-editor to 2.2.1

### PR DESCRIPTION
**Pull request by xrmx**

### CODE REVIEW

**Comment by abogushov** [comment]
Thanks!

**Comment by xrmx** [comment]
@abogushov hello, any chance you can release a new version please? Thanks!

**Comment by abogushov** [comment]
@xrmx I have created new release but there are problems with PyPI it returned 400 during upload (https://travis-ci.org/github/abogushov/django-admin-json-editor/jobs/686008467). I will try to fix it.

**Comment by xrmx** [comment]
@abogushov thanks a lot! Much appreciated

**Comment by xrmx** [comment]
@abogushov failing upload should be fixed in #29

**Pull request merged**
